services:
  - type: web
    name: solar-data-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node ./dist/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8001

